name: Code Coverage

on:
  push:
    branches: [ master, codecov ]
  pull_request:
    branches: [ master, codecov ]

jobs:
  publish-code-coverage:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 1.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8      
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          run: mvn jacoco:report
      - uses: codecov/codecov-action@v1
